// Code generated by qtc from "open_door.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//

//line views/images/open_door.qtpl:6
package images

//line views/images/open_door.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/images/open_door.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/images/open_door.qtpl:6
func StreamOpenDoor(qw422016 *qt422016.Writer) {
//line views/images/open_door.qtpl:6
	qw422016.N().S(`image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAABmklEQVRYhWNgGOSAkRLNoQ1X2T5zfopkZ2Vu+vHrrxxMfGeFJUXmIgOcBrl3HP+PTyMTIyMDCzMjg4wwF4OHkRSDn54QAwMDA4NH5wmyHILLUyz4NM3IMEfhv/70k2Hf5RcMJ2+9YdCVF2BwN5RikBLkJKiPEMiYcRKnHF4HwsDD118Z9l1+wXDl4QcGMzURhrowXQYBbjaSHEEuIMqB7WuvMETYyDNE2ykysLEwEVSPL0SQATEhTZQDGRgYGBx0JIhVyhDoYgZnywlgT+YT1xDnCcLBMcBg1IGUglEHUgpGHUgpGHUgpWDUgZSC4e/AKdtvUsMdOAHFDqRa2x4HoNiB2Z7q1HAHTjD80yCtwagDKQWjDqQUjDqQUjDqQErBqAMpBaMOpBQMegcSPQSsLs3HoC3Dz6AsycsgJ8LNwIo2TqjADzGK2kPARDWIXTuPSDH+ZzZmZ2NyZGFkcvn5+6+6AA/rTw1pfjZVSV52VUk+BmMZDrgD6TKIjg8YzzzDKvzujx4LM6MdFzuz58/ffy1//fnHA5OnpgMBms9S/wcaQrQAAAAASUVORK5CYII=`)
//line views/images/open_door.qtpl:8
}

//line views/images/open_door.qtpl:8
func WriteOpenDoor(qq422016 qtio422016.Writer) {
//line views/images/open_door.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/images/open_door.qtpl:8
	StreamOpenDoor(qw422016)
//line views/images/open_door.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line views/images/open_door.qtpl:8
}

//line views/images/open_door.qtpl:8
func OpenDoor() string {
//line views/images/open_door.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line views/images/open_door.qtpl:8
	WriteOpenDoor(qb422016)
//line views/images/open_door.qtpl:8
	qs422016 := string(qb422016.B)
//line views/images/open_door.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line views/images/open_door.qtpl:8
	return qs422016
//line views/images/open_door.qtpl:8
}
