POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"{{username}}","password":"{{password}}"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
POST https://{{host}}/api/reports/by_tags
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "recruiter_id":33,
  "start_date":"2021-04-01",
  "end_date":"2021-04-29",
  "includes": [1,2]
 }
###
POST https://{{host}}/api/main/getCandidatesAmountByTags
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "recruiter_id":33,
  "start_date":"2021-04-01",
  "end_date":"2021-04-29",
 }

###  "vacancy_id":15,"company_id":9,

> {%
    client.test("response is ok", response.status === 200);

    // test
    client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
 });

    client.test("json contain data", function() {
    var b = response.body;
  client.assert(len(b.Main) > 0, "Main must be not null");
  client.assert(b.Reject != null, "must containt url ");

 });

%}