POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"ed.nazarenkoff@gmail.com","password":"g%S3LmYxz*&RYIn@iQ7B"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"ni@gamayun.sk","password":"12345"}
###
POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"alona.ryd18@gmail.com","password":"alona.ryd"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"test@test.com","password":"1111"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}

###
GET https://{{host}}/api/main/dashBoardAdmin
Authorization:Bearer {{auth_token}}
###
POST https://{{host}}/api/main/viewAllVacancyInCompany/null/1
Authorization:Bearer {{auth_token}}
###
POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"julia@uppeople.co","password":"g%S3LmYxz*&RYIn@iQ7B"}

> {%
    client.global.set("auth_token", response.body.access_token);

    // test
    client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
 });

    client.test("json contain data", function() {
    var b = response.body;
  client.assert(b.formActions[0].type == "redirect", "type must equals 'redirect'");
  client.assert(b.formActions[0].url, "must containt url "+ b.formActions[0]);

 });

%}

###
GET https://{{host}}/api/main/dashBoardAdmin
Authorization:Bearer {{auth_token}}
###
POST https://{{host}}/api/main/viewCandidatesFreelancerOnVacancies/1
Authorization:Bearer {{auth_token}}
###
GET https://{{host}}/api/admin/all-staff
Authorization:Bearer {{auth_token}}
Accept: */*
Content-Type: application/json
Origin: null
Pragma: no-cache
Cache-Control: no-cache
Accept-Language: en-gb
