
POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"ed.nazarenkoff@gmail.com","password":"g%S3LmYxz*&RYIn@iQ7B"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
POST https://{{host}}/api/main/addNewCandidate
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Ruslan Bikchentaev2",
  "selectPlatform":[],"selectSeniority":[],"selectedTag":{"id":1,"label":"first contact","value":"first contact"},"date":"2020-12-21","salary":"","language":"","phone":"","skype":"","email":"","linkedIn":"","resume":"","comment":"","selectedVacancies":[]
}

###
POST https://{{host}}/api/main/allCandidates/1
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "search": "Ruslan Bikchentaev",
  "selectPlatform":[],"selectSeniority":[],"selectedTag":{"id":1,"label":"first contact","value":"first contact"},"date":"2020-12-21","salary":"","language":"","phone":"","skype":"","email":"","linkedIn":"","resume":"","comment":"","selectedVacancies":[]
}