
POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"{{username}}","password":"{{password}}"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
GET https://{{host}}/api/main/viewOneCandidate/9977
Authorization:Bearer {{auth_token}}
Content-Type: application/json


###
GET https://{{host}}/api/main/allCandidates/2000
Authorization:Bearer {{auth_token}}
Content-Type: application/json

###
POST https://{{host}}/api/main/allCandidates/1
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "search": "Ruslan Bikchentaev",
  "selectPlatform":[],"selectSeniority":[],"selectedTag":{"id":1,"label":"first contact","value":"first contact"},
  "date":"2020-12-21","salary":"","language":"","phone":"","skype":"","email":"","linkedIn":"","resume":"","comment":"","selectedVacancies":[]
}
###
POST https://{{host}}/api/main/returnAllCandidates/1
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "search": "Oleg",
  "selectCompanies":[{"id":3,"label":"AppsFlyer","value":"appsflyer"}],
  "selectPlatform":[],"selectSeniority":[],"selectedTag":{"id":1,"label":"first contact","value":"first contact"},
  "date":"2020-12-21",
  "salary":"","language":"","phone":"","skype":"","email":"","linkedIn":"","resume":"","comment":"","selectedVacancies":[]
}
###
OPTIONS https://{{host}}/api/main/addNewCandidate
Authorization:Bearer {{auth_token}}
Content-Type: application/json
Origin: chrome-extension://nhpgjjldecdiljjcbhdcikechkgdadhf
###
POST https://{{host}}/api/main/addNewCandidate
Authorization:Bearer {{auth_token}}
Content-Type: application/json
Origin: test:{{host}}

{"linkedin":"https://www.linkedin.com/in/dmitriy-druzhbin-73ba003/","name":"Dmitriy Druzhbin","link":"","tag_id":1,"location":"","date":"2020-01-01","salary":"","language":"Beginner","email":"mangoose@the-clu.com","phone":"","skype":"","comments":"","avatar":"https://media-exp1.licdn.com/dms/image/C4D03AQEfsZB2qusqPA/profile-displayphoto-shrink_400_400/0/1516304960310?e=1616630400&v=beta&t=xjDBu2CR2T_iQ-shTdFBJSRVj41G71AO-t_WzEUyyts","platform_id":{"value":"2","valid":true},"vacancies_ids":"[]","seniority_id":{"value":"4","valid":true},"url":""}

###
POST https://{{host}}/api/main/editCandidate/s232%2022s
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{"name":"Ruslan http-test 1",
  "selectPlatform":{"id":36,"label":"Backend","value":"backend"},
  "selectSeniority":{"id":5,"label":"Architect","value":"architect"},
  "selectedTag":{"id":1,"label":"first contact","value":"first contact"},
  "date":"2020-12-27",
  "salary":"4500-5000",
  "language":"Pre-Intermediate",
  "phone":"800-900-600",
  "skype":"ruslan_bik",
  "email":"ruslan@artel.ws",
  "linkedIn":"https://www.linkedin.com/in/vladislav-yena/",
  "resume":"https://www.linkedin.com/",
  "comment":"test",
  "selectedVacancies":[]
}

### follow UP
POST https://{{host}}/api/main/saveFollowUp
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{"candidate_id":9977,"date_follow_up":"01.01.2021","comment":"Test testedit"
}

###
GET https://{{host}}/api/admin/returnLogsForCand/10000
Authorization:Bearer {{auth_token}}

###
GET https://{{host}}/api/main/returnOptionsForSelects
Authorization:Bearer {{auth_token}}
