POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"{{username}}","password":"{{password}}"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
POST https://{{host}}/api/main/returnAllCompanies/1
Authorization:Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "^B",
  "email": "a"
}