POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"{{username}}","password":"{{password}}"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
POST https://{{host}}/api/v1/table/candidates/form
Content-Type: multipart/form-data;Boundary=9279060804085932;
Authorization: Bearer {{auth_token}}

--9279060804085932
Content-Disposition: form-data; name="table"

users
--9279060804085932--

###