POST https://{{host}}/api/auth/login
Content-Type: application/json

{"email":"{{username}}","password":"{{password}}"}

> {%
    client.global.set("auth_token", response.body.access_token);
%}
###
GET https://{{host}}/api/get_recruiter_vacancies
Content-Type: application/x-www-form-urlencoded
Authorization:Bearer {{auth_token}}

###
POST https://{{host}}/api/get_candidate_info
Content-Type: multipart/form-data;boundary=9279060804085932;
Authorization:Bearer {{auth_token}}

--9279060804085932
Content-Disposition: form-data; name="url"

https://www.linkedin.com/in/alexandr-tretiakov-ba83105
--9279060804085932--

###
POST https://{{host}}/api/get_candidate_info
Authorization:Bearer {{auth_token}}
Content-Type: multipart/form-data;;boundary=9279060804085932;

--9279060804085932
Content-Disposition: form-data; name="url"

https://www.linkedin.com/in/alexandr-tretiakov-ba831051/
--9279060804085932--
###
POST https://{{host}}/api/get_recruiter_vacancies
Authorization:Bearer {{auth_token}}
###
POST https://{{host}}/api/authorize
Content-Type: application/x-www-form-urlencoded

email=Julia%40uppeople.co&password=g%25S3LmYxz*%26RYIn%40iQ7B