POST https://{{host}}/api/get_candidate_info
Content-Type: application/x-www-form-urlencoded

url=https://www.linkedin.com/in/nikita-taktashev/
###
POST https://{{host}}/api/get_candidate_info
Content-Type: application/x-www-form-urlencoded

url=https://www.linkedin.com/in/dmitriy-druzhbin-73ba003/
###
POST https://{{host}}/api/authorize
Content-Type: application/x-www-form-urlencoded

email=Julia%40uppeople.co&password=g%25S3LmYxz*%26RYIn%40iQ7B