POST https://{{host}}/api/get_candidate_info
Content-Type: application/x-www-form-urlencoded

url=https://www.linkedin.com/in/nikita-taktashev/
###
POST https://{{host}}/api/get_candidate_info
Content-Type: application/x-www-form-urlencoded

url=https://www.linkedin.com/in/dmitriy-druzhbin-73ba003/