package db

const SQL_GET_TYPES = "SELECT typname, oid FROM pg_type WHERE typname::text=ANY($1)"

// Table names
const TABLE_Tags = "tags"
const TABLE_Candidates = "candidates"
const TABLE_CandidatesOnVacanciesFreelancers = "candidates_on_vacancies_freelancers"
const TABLE_CandidatesToCompanies = "candidates_to_companies"
const TABLE_CandidatesToSkills = "candidates_to_skills"
const TABLE_ChromeExtensionSelector = "chrome_extention_selectors"
const TABLE_Comments = "comments"
const TABLE_CommentsForCandidates = "comments_for_candidates"
const TABLE_CommentsForCompanies = "comments_for_companies"
const TABLE_Companies = "companies"
const TABLE_Contacts = "contacts"
const TABLE_ContactsToPlatforms = "contacts_to_platforms"
const TABLE_Dictionary = "dictionary"
const TABLE_EmailTemplates = "email_templates"
const TABLE_FAQCategories = "faq_categories"
const TABLE_FAQQuestions = "faq_qustions"
const TABLE_FavoritesPlatforms = "favorites_platforms"
const TABLE_Firma = "firma"
const TABLE_FormBlocks = "form_blocks"
const TABLE_FormFields = "form_fields"
const TABLE_Forms = "forms"
const TABLE_FreelancersVacancies = "freelancers_vacancies"
const TABLE_Homepages = "homepages"
const TABLE_InBoxes = "in_boxes"
const TABLE_IntRevCandidates = "int_rev_candidates"
const TABLE_Languages = "languages"
const TABLE_LinkedinCandidates = "linkedin_candidates"
const TABLE_Links = "links"
const TABLE_LocationForVacancies = "location_for_vacancies"
const TABLE_Logs = "logs"
const TABLE_Management = "management"
const TABLE_Meetings = "meetings"
const TABLE_Migrations = "migrations"
const TABLE_OauthAccessTokens = "oauth_access_tokens"
const TABLE_OauthAuthCodes = "oauth_auth_codes"
const TABLE_OauthClients = "oauth_clients"
const TABLE_OauthPersonalAccessClients = "oauth_personal_access_clients"
const TABLE_OauthRefreshTokens = "oauth_refresh_tokens"
const TABLE_Partners = "partners"
const TABLE_PasswordResets = "password_resets"
const TABLE_PatternsList = "patterns_list"
const TABLE_Platforms = "platforms"
const TABLE_SentEmails = "sended_emails"
const TABLE_Seniorities = "seniorities"
const TABLE_Skills = "skills"
const TABLE_StatusForVacs = "status_for_vacs"
const TABLE_Statuses = "statuses"
const TABLE_StopLists = "stoplists"
const TABLE_TodoLists = "todolists"
const TABLE_UserToPlatforms = "user_to_platforms"
const TABLE_UserToVacancies = "user_to_vacancies"
const TABLE_Users = "users"
const TABLE_Vacancies = "vacancies"
const TABLE_VacanciesToCandidates = "vacancies_to_candidates"
const TABLE_WPCommentMeta = "wp_commentmeta"
const TABLE_WPComments = "wp_comments"
const TABLE_WPLinks = "wp_links"
const TABLE_WPOptions = "wp_options"
const TABLE_WPPostMeta = "wp_postmeta"
const TABLE_WPPosts = "wp_posts"
const TABLE_WPSimplyStaticPages = "wp_simply_static_pages"
const TABLE_WPTermRelationships = "wp_term_relationships"
const TABLE_WPTermTaxonomy = "wp_term_taxonomy"
const TABLE_WPTermMeta = "wp_termmeta"
const TABLE_WPTerms = "wp_terms"
const TABLE_WPUserMeta = "wp_usermeta"
const TABLE_WPUsers = "wp_users"

//Tag values
const TAG_FirstContact = "first contact"
const TAG_Interested = "interested"
const TAG_Reject = "reject"
const TAG_NoAnswer = "no answer"
const TAG_ClosedToOffers = "closed to offers"
const TAG_LowSalary = "low salary rate"
const TAG_WasContactedEarlier = "was contacted earlier"
const TAG_DoesNotLikeProject = "does not like the project"
const TAG_TermsDoNotFit = "terms don’t fit"
const TAG_RemoteOnly = "remote only"
const TAG_DoesNotFit = "does not fit"

//Status values
const STATUS_Hot = "Hot"
const STATUS_Open = "Open"
const STATUS_Closed = "Closed"
const STATUS_Paused = "Paused"

//Status for vacancies values
const STATUS_FOR_VAC_Interview = "Interview"
const STATUS_FOR_VAC_Test = "Test"
const STATUS_FOR_VAC_FinalInterview = "Final Interview"
const STATUS_FOR_VAC_Offer = "OFFER"
const STATUS_FOR_VAC_Hired = "Hired"
const STATUS_FOR_VAC_WR = "WR"
const STATUS_FOR_VAC_Review = "Review"
const STATUS_FOR_VAC_Rejected = "Rejected"
const STATUS_FOR_VAC_OnHold = "On hold"

//Seniorities values
const SENIORITY_Jun = "Jun"
const SENIORITY_Mid = "Mid"
const SENIORITY_Sen = "Sen"
const SENIORITY_Lead = "Lead"
const SENIORITY_Architect = "Architect"
const SENIORITY_JunMid = "Jun-Mid"
const SENIORITY_MidSen = "Mid-Sen"
const SENIORITY_SenLead = "Sen-Lead"

var tagIds TagIdMap
var statusesIds StatusIdMap
var statusesForVacIds StatusForVacIdMap
var seniorityIds SeniorityIdMap
var platformIds PlatformsIdMap
