// Code generated by qtc from "search_panel.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//
// .

//line views/forms/search_panel.qtpl:5
package forms

//line views/forms/search_panel.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/forms/search_panel.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/forms/search_panel.qtpl:5
func StreamSearchPanel(qw422016 *qt422016.Writer) {
//line views/forms/search_panel.qtpl:5
	qw422016.N().S(`
    <h2 class="font_2" style="font-size:26px; line-height:1.2em;"><span style="font-style:italic;"><span style="font-size:26px;">
    <span style="font-family:times new roman,times,serif;"><span style="color:#292929;">Пошук</span></span></span></span>
     </h2>
   <form id="fSearch" action="/api/v1/search/" method="GET" target="#content" novalidate
   onsubmit="$('select.suggestions-constraints').hide(); return saveForm(this, showObject, function(error, status) { $('#content').html(error.responseText); } );" style="width:1100px">
        <div class="w3-clear">
         <input type="hidden" name="html" value="true"/>
         <input type="hidden" name="counter" value="5"/>
         <input id="inpS" name="name" type="search" placeholder="Введіть початкові літери" required
            autocapitalize="none" autocorrect="off" autocomplete="off">
         <div class="suggestions-wrapper">
            <span class="suggestions-addon" data-addon-type="spinner" style="left: -97px; top: 1px; height: 42px; width: 42px;"></span>
         <select name="id" size=10 class="suggestions-constraints" style="left: -399.109375px; top: 50px;"></select>
         <div class="suggestions-suggestions" style="position: absolute; display: none; left: -311.109375px; top: 43px; width: 256.109375px;">
         </div>
         </div>
         <button type="search"><i class="fa fa-search"></i></button>
       </div>
        <output></output>
        <progress value='0' max='100' hidden > </progress>
    </form>
       <form id="fSearchAnalog" action="/api/v1/search/analog/" method="GET" target="#content" novalidate
         onsubmit="return saveForm(this, showObject, function(error, status) { $('#content').html(error.responseText); } );" style="width:1100px">
    <input name="name" type="search" placeholder="Введіть літери for analog" required autocomplete="off">
         <button type="search"><i class="fa fa-search"></i></button>
   </form>

`)
//line views/forms/search_panel.qtpl:33
}

//line views/forms/search_panel.qtpl:33
func WriteSearchPanel(qq422016 qtio422016.Writer) {
//line views/forms/search_panel.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/forms/search_panel.qtpl:33
	StreamSearchPanel(qw422016)
//line views/forms/search_panel.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line views/forms/search_panel.qtpl:33
}

//line views/forms/search_panel.qtpl:33
func SearchPanel() string {
//line views/forms/search_panel.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line views/forms/search_panel.qtpl:33
	WriteSearchPanel(qb422016)
//line views/forms/search_panel.qtpl:33
	qs422016 := string(qb422016.B)
//line views/forms/search_panel.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line views/forms/search_panel.qtpl:33
	return qs422016
//line views/forms/search_panel.qtpl:33
}
