// Code generated by qtc from "pdf.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//

//line views/output/pdf.qtpl:4
package output

//line views/output/pdf.qtpl:4
import (
	"github.com/ruslanBik4/uppeople/db"
)

//line views/output/pdf.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/output/pdf.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/output/pdf.qtpl:9
type ItemsView struct {
	*db.ItemsFields
	NamePolymers    string
	NameReinforcing string
	NameTypePrepeg  string
}

//line views/output/pdf.qtpl:17
func (i *ItemsView) StreamViewPrepeg(qw422016 *qt422016.Writer) {
//line views/output/pdf.qtpl:17
	qw422016.N().S(`
<div style="position:absolute;left:50%;margin-left:-297px;top:0px;width:595px;height:842px;border-style:outset;overflow:hidden">
<div style="position:absolute;left:0px;top:0px">
<div style="position:absolute;left:32.00px;top:120.00px;font:bold;font-size:14;" class="cls_002">ТзОВ «Альфа Пласт»</div>
<div style="position:absolute;left:32.00px;top:148.00px;" class="cls_002">Dealer/Manufacturer in your area</div>
<div style="position:absolute;left:335.00px;top:120.00px" class="cls_002">Ukraine, Kiev, 17/46 Donca str.</div>
<div style="position:absolute;left:335.00px;top:148.09px" class="cls_002"><span class="cls_002">+380(44) 408 34 64</span></div>
<div style="position:absolute;left:32.00px;top:188.45px;font:bold;font-size:24;" class="cls_002">`)
//line views/output/pdf.qtpl:24
	qw422016.N().S(i.Manufacturer.String)
//line views/output/pdf.qtpl:24
	qw422016.N().S(` `)
//line views/output/pdf.qtpl:24
	qw422016.N().S(i.Marka.String)
//line views/output/pdf.qtpl:24
	qw422016.N().S(`</div>
<div style="position:relative;left:0px;top:26px" class="cls_002">`)
//line views/output/pdf.qtpl:25
	qw422016.N().S(i.Notes.String)
//line views/output/pdf.qtpl:25
	qw422016.N().S(`</div>
<div style="position:absolute;left:48.00px;top:310px" class="cls_002"><span class="cls_002">Type of prepeg</span></div>
<div style="position:absolute;left:314.00px;top:310" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:27
	qw422016.N().S(i.NameTypePrepeg)
//line views/output/pdf.qtpl:27
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:334" class="cls_002"><span class="cls_002">Name of Polymer</span></div>
<div style="position:absolute;left:314.00px;top:334" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:29
	qw422016.N().S(i.NamePolymers)
//line views/output/pdf.qtpl:29
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:358" class="cls_002"><span class="cls_002">Filler configuration</span></div>
<div style="position:absolute;left:314.00px;top:358" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:31
	qw422016.N().S(i.Content_filler.String)
//line views/output/pdf.qtpl:31
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:382" class="cls_002"><span class="cls_002">Configuration of reinforcing filler</span></div>
<div style="position:absolute;left:314.00px;top:382" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:33
	qw422016.N().S(i.NameReinforcing)
//line views/output/pdf.qtpl:33
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:406" class="cls_002"><span class="cls_002">Type of fibre filler</span></div>
<div style="position:absolute;left:314.00px;top:406" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:35
	qw422016.N().S(i.Type_of_fibre_filler.String)
//line views/output/pdf.qtpl:35
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:454" class="cls_002"><span class="cls_002">Product characterisation</span></div>
<div style="position:absolute;left:256.00px;top:454" class="cls_002"><span class="cls_002">Test method</span></div>
<div style="position:absolute;left:418.00px;top:454" class="cls_002"><span class="cls_002">Test result</span></div>
<div style="position:absolute;left:48.00px;top:478" class="cls_002"><span class="cls_002">Density, kg/m³</span></div>
<div style="position:absolute;left:256.00px;top:478" class="cls_002"><span class="cls_002">ISO 1183</span></div>
<div style="position:absolute;left:418.00px;top:478" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:41
	qw422016.N().F(i.Density.Float64)
//line views/output/pdf.qtpl:41
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:502" class="cls_002"><span class="cls_002">Tensile modulus, GPa</span></div>
<div style="position:absolute;left:256.00px;top:502" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:43
	qw422016.N().S(i.Tensile_modulus_iso.String)
//line views/output/pdf.qtpl:43
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:418.00px;top:502" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:44
	qw422016.N().S(i.Tensile_modulus.String)
//line views/output/pdf.qtpl:44
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:526" class="cls_002"><span class="cls_002">Tensile strength, MPa</span></div>
<div style="position:absolute;left:256.00px;top:526" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:46
	qw422016.N().S(i.Tensile_strength_iso.String)
//line views/output/pdf.qtpl:46
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:418.00px;top:526" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:47
	qw422016.N().S(i.Tensile_strength.String)
//line views/output/pdf.qtpl:47
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:550" class="cls_002"><span class="cls_002">Flexural strength, MPa</span></div>
<div style="position:absolute;left:256.00px;top:550" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:49
	qw422016.N().S(i.Flexural_strength_iso.String)
//line views/output/pdf.qtpl:49
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:418.00px;top:550" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:50
	qw422016.N().S(i.Flexural_strength.String)
//line views/output/pdf.qtpl:50
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:574" class="cls_002"><span class="cls_002">Flexural modulus, GPa</span></div>
<div style="position:absolute;left:256.00px;top:574" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:52
	qw422016.N().S(i.Flexural_modulus_iso.String)
//line views/output/pdf.qtpl:52
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:418.00px;top:574" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:53
	qw422016.N().S(i.Flexural_modulus.String)
//line views/output/pdf.qtpl:53
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:598" class="cls_002"><span class="cls_002">Flammability, class</span></div>
<div style="position:absolute;left:256.00px;top:598" class="cls_002"><span class="cls_002">UL 94</span></div>
<div style="position:absolute;left:418.00px;top:598" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:56
	qw422016.N().S(i.Flammability.String)
//line views/output/pdf.qtpl:56
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:622" class="cls_002"><span class="cls_002">Charpy impact strength, kJ/m²</span></div>
<div style="position:absolute;left:256.00px;top:622" class="cls_002"><span class="cls_002">ISO 179-1</span></div>
<div style="position:absolute;left:418.00px;top:622" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:59
	qw422016.N().S(i.Charpy_impact_strength.String)
//line views/output/pdf.qtpl:59
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:646" class="cls_002"><span class="cls_002">Shrincage, %</span></div>
<div style="position:absolute;left:256.00px;top:646" class="cls_002"><span class="cls_002">ISO 2577</span></div>
<div style="position:absolute;left:418.00px;top:646" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:62
	qw422016.N().S(i.Shrinkage.String)
//line views/output/pdf.qtpl:62
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:670" class="cls_002"><span class="cls_002">Water absorbation, %</span></div>
<div style="position:absolute;left:256.00px;top:670" class="cls_002"><span class="cls_002">ISO 62</span></div>
<div style="position:absolute;left:418.00px;top:670" class="cls_002"><span class="cls_002">`)
//line views/output/pdf.qtpl:65
	qw422016.N().S(i.Water_absorption.String)
//line views/output/pdf.qtpl:65
	qw422016.N().S(`</span></div>
<div style="position:absolute;left:48.00px;top:718" class="cls_004"><span class="cls_004">Processing methods</span></div>
<div style="position:absolute;left:250.00px;top:718">`)
//line views/output/pdf.qtpl:67
	qw422016.N().S(i.Methods_recycling.String)
//line views/output/pdf.qtpl:67
	qw422016.N().S(`</div>
<div style="position:absolute;left:48.00px;top:742">Application area</div>
<div style="position:absolute;left:250.00px;top:742">`)
//line views/output/pdf.qtpl:69
	qw422016.N().S(i.Using_sectors.String)
//line views/output/pdf.qtpl:69
	qw422016.N().S(`</div>
</div>
`)
//line views/output/pdf.qtpl:71
}

//line views/output/pdf.qtpl:71
func (i *ItemsView) WriteViewPrepeg(qq422016 qtio422016.Writer) {
//line views/output/pdf.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/output/pdf.qtpl:71
	i.StreamViewPrepeg(qw422016)
//line views/output/pdf.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line views/output/pdf.qtpl:71
}

//line views/output/pdf.qtpl:71
func (i *ItemsView) ViewPrepeg() string {
//line views/output/pdf.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
//line views/output/pdf.qtpl:71
	i.WriteViewPrepeg(qb422016)
//line views/output/pdf.qtpl:71
	qs422016 := string(qb422016.B)
//line views/output/pdf.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
//line views/output/pdf.qtpl:71
	return qs422016
//line views/output/pdf.qtpl:71
}
