name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1days # Setting this to 0 will delete all artifacts

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -o httpgo .

    - name: Test
      run: go test -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: httpgo
        # A file, directory or wildcard pattern that describes what to upload
        path: httpgo

    - name: Upload a cfg Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: cfg
        # A file, directory or wildcard pattern that describes what to upload
        path: cfg/

 # deploy_prod:
  #  name: Generate systemd unit file for go services
  #  runs-on: ubuntu-latest
  #  steps:
    - shell: bash
      env:
        PROD_PGDATABASE: ${{secrets.PGDATABASE }}
        PROD_PGUSER: ${{secrets.PGUSER }}
        PROD_PGPASSWORD: ${{secrets.PGPASS }}
        TBTOKEN: ${{secrets.TBTOKEN }}
        TBCHATID: ${{secrets.TBCHATID }}
      run: |
        for sd_unit in systemd/*.service; do

          sed -i "s|PGHOST=|PGHOST=localhost|g" $sd_unit
          sed -i "s|PGDATABASE=|PGDATABASE=$PROD_PGDATABASE|g" $sd_unit
          sed -i "s|PGUSER=|PGUSER=$PROD_PGUSER|g" $sd_unit
          sed -i "s|PGPASSWORD=|PGPASSWORD=$PROD_PGPASSWORD|g" $sd_unit
          sed -i "s|TBTOKEN=|TBTOKEN=$TBTOKEN|g" $sd_unit
          sed -i "s|TBCHATID=|TBCHATID=$TBCHATID|g" $sd_unit

        done

    - name: Upload a systemd Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: systemd
        # A file, directory or wildcard pattern that describes what to upload
        path: systemd/

    - name: Copy cfg of DB via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_PROD_HOST }}
        USERNAME: ${{ secrets.SSH_PROD_USER }}
        #PORT: 22
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "cfg/DB/"
        target: "/opt/uppeople"

    - name: Copy httpgo via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_PROD_HOST }}
        USERNAME: ${{ secrets.SSH_PROD_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "httpgo"
        target: "/opt/uppeople/"

    - name: stop services on pm-db.net
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ${{secrets.SSH_PROD_USER }}
        HOST:     ${{secrets.SSH_PROD_HOST }}
        KEY:      ${{ secrets.SSH_KEY }}
        SCRIPT:   |
          # Next lines it's workaround for the error scp: ... Text file busy
          # And we need stop service before replacing golang binaries

          for sd_unit in /opt/uppeople/systemd/*.service; do

            sudo systemctl stop $(basename "$sd_unit")
            sudo cp $sd_unit /etc/systemd/system/
          done
    - name: Copy systemd files via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_PROD_HOST }}
        USERNAME: ${{ secrets.SSH_PROD_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "systemd/*.service"
        target: "/opt/uppeople/"

    - name: Restart services
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ${{secrets.SSH_PROD_USER }}
        HOST:     ${{secrets.SSH_PROD_HOST }}
        KEY:      ${{ secrets.SSH_KEY }}
        SCRIPT: |
          sudo systemctl daemon-reload
          for sd_unit in /opt/uppeople/systemd/*.service; do
            #sd_unit = $(echo "$sd_unit" | cut -f 1 -d '.')

            sudo systemctl enable $(basename "$sd_unit")
            sudo systemctl restart $(basename "$sd_unit")
            sudo systemctl status $(basename "$sd_unit") -l

          done
